function [FH,SPH,PBH,TBH]=CalSensFig
% FH  - Figure handle
% SPH - Subplot handle
% PBH - Pushbutton handles
% TBH - Textbox handles

FH=figure;


SC=get(0,'ScreenSize');
FH.Position=[25 SC(4)-650 800 600]; 
% FH.Position=[20 300 800 600];
FH.NumberTitle='off';
FH.MenuBar='none';
FH.Resize='off';
FH.Name='Sensor Calibration Window';


SPH(1)=subplot(221);
SPH(1).UserData=false;SPH(1).ButtonDownFcn= 'h=gco; h.UserData=true;';
% uicontrol(FH,'Style','Text','String','Click on subplot to undock!', ...
%              'FontSize',10,'Fore','red','Position',[135 305 200 20]);
SPH(2)=subplot(222);
xlabel('t [s]')
SPH(3)=subplot(223);
xlabel('t [s]')

uicontrol(FH,'Style','Text','String','1st', ...
             'FontSize',10,'Fore','blue','Position',[30 520 25 20]);
uicontrol(FH,'Style','Text','String','2nd', ...
             'FontSize',10,'Fore','blue','Position',[390 520 25 20]);
uicontrol(FH,'Style','Text','String','3rd', ...
             'FontSize',10,'Fore','blue','Position',[30 220 25 20]);

UIH(1) = uipanel('Title','Calibration Panel','FontSize',10,...
             'BackgroundColor','white','Fore','blue',...
             'Position',[.52 .02 .46 .46]);

PBH(1) = uicontrol('Parent',UIH(1),'Style','Push','String','Accept',...
              'Callback','h=gco; h.UserData=true;', ...
              'UserData',false,'Position',[10 10 70 25]);
PBH(2) = uicontrol('Parent',UIH(1),'Style','Push','String','Next',...
              'Callback','h=gco; h.UserData=true;', ...
              'UserData',false,'Position',[200 10 70 25]);
PBH(3) = uicontrol('Parent',UIH(1),'Style','Push','String','Done',...
              'Callback','h=gco; h.UserData=true;', ...
              'UserData',false,'Position',[280 10 70 25]);
            
uicontrol(UIH(1),'Style','Text','String',...
                ' Present calibration:                       mV/unit', ...
                'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','Left',...
                'Position',[10 210 260 20],'FontSize',10);            
uicontrol(UIH(1),'Style','Text','String',...
                '                                                    unit/mV', ...
                'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','Left',...
                'Position',[10 190 260 20],'FontSize',10);            

uicontrol(UIH(1),'Style','Text','String',...
                ' Suggested calibration:                   mV/unit     Diff:          %', ...
                'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','Left',...
                'Position',[10 150 370 20],'FontSize',10);            
uicontrol(UIH(1),'Style','Text','String',...
                '                                                    unit/mV', ...
                'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','Left',...
                'Position',[10 130 260 20],'FontSize',10);       

uicontrol(UIH(1),'Style','Text','String',...
                ' C.O.V.:                                              %', ...
                'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','Left',...
                'Position',[10 90 260 20],'FontSize',10);            
uicontrol(UIH(1),'Style','Text','String',...
                ' Crosstalk   2nd             % 3rd             %', ...
                'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','Left',...
                'Position',[10 70 260 20],'FontSize',10);       
              

TBH(1)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[147 211 65 18],'FontSize',10);            
TBH(2)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[147 191 65 18],'FontSize',10);            
TBH(3)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[147 151 65 18],'FontSize',10);     
TBH(4)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[310 151 35 18],'FontSize',10);                 
TBH(5)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[147 131 65 18],'FontSize',10);     
TBH(6)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[192 91 45 18],'FontSize',10);     
TBH(7)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[107 71 45 18],'FontSize',10);     
TBH(8)=uicontrol(UIH(1),'Style','Text','String','-', ...
                'BackgroundColor',[.9 .9 .9],'HorizontalAlignment','Right',...
                'Position',[192 71 45 18],'FontSize',10);     
              
